export default {
  collection: 'case_files',
  validator: {
    $jsonSchema: {
      bsonType: 'object',
      required: ['caseFileNumber', 'caseTitle', 'registryId', 'courtStationId'],
      properties: {
        caseFileNumber: { bsonType: 'string', description: 'Case file number is required' },
        caseTitle: { bsonType: 'string', description: 'Case title is required' },
        caseType: { bsonType: 'string' },
        registryId: { bsonType: 'string', description: 'Registry ID is required' },
        courtStationId: { bsonType: 'string', description: 'Court station ID is required' },
        courtRoom: { bsonType: ['string', 'null'] },
        caseStatus: { bsonType: 'string' },
        fileStatus: { bsonType: 'string' },
        fileCategory: { bsonType: 'string' },
        currentHolderId: { bsonType: ['string', 'null'] },
        currentLocation: { bsonType: 'string' },
        dateOpened: { bsonType: ['date', 'null'] },
        parties: { bsonType: ['string', 'null'] },
        createdAt: { bsonType: 'date' },
        updatedAt: { bsonType: 'date' },
      },
    },
  },
  indexes: [
    { key: { caseFileNumber: 1 }, options: { unique: true } },
    { key: { registryId: 1 } },
    { key: { courtStationId: 1 } },
    { key: { currentHolderId: 1 } },
    { key: { fileStatus: 1 } },
    { key: { caseStatus: 1 } },
    { key: { caseFileNumber: 'text', caseTitle: 'text' } },
  ],
};
