export default {
  collection: 'file_movements',
  validator: {
    $jsonSchema: {
      bsonType: 'object',
      required: ['caseFileId', 'fromHolderId', 'movementType', 'reason'],
      properties: {
        caseFileId: { bsonType: 'string', description: 'Case file ID is required' },
        fromHolderId: { bsonType: 'string', description: 'From holder ID is required' },
        toHolderId: { bsonType: ['string', 'null'] },
        fromRegistryId: { bsonType: ['string', 'null'] },
        toDestination: { bsonType: 'string' },
        movementType: { bsonType: 'string' },
        reason: { bsonType: 'string' },
        dateIssued: { bsonType: 'date' },
        timeIssued: { bsonType: 'date' },
        expectedReturnDate: { bsonType: ['date', 'null'] },
        actualReturnDate: { bsonType: ['date', 'null'] },
        status: { bsonType: 'string' },
        remarks: { bsonType: ['string', 'null'] },
        digitalSignature: { bsonType: ['string', 'null'] },
        acknowledgedBy: { bsonType: ['string', 'null'] },
        acknowledgedAt: { bsonType: ['date', 'null'] },
        createdAt: { bsonType: 'date' },
      },
    },
  },
  indexes: [
    { key: { caseFileId: 1 } },
    { key: { fromHolderId: 1 } },
    { key: { toHolderId: 1 } },
    { key: { status: 1 } },
    { key: { dateIssued: -1 } },
    { key: { expectedReturnDate: 1 } },
  ],
};
