export default {
  collection: 'trips',
  validator: {
    $jsonSchema: {
      bsonType: 'object',
      required: ['tripId', 'destination', 'purpose', 'departureDate', 'status'],
      properties: {
        tripId: { bsonType: 'string', description: 'Trip ID is required' },
        vehicleId: { bsonType: ['string', 'null'] },
        userId: { bsonType: 'string', description: 'User ID is required' },
        driverId: { bsonType: ['string', 'null'] },
        requestingOfficerId: { bsonType: ['string', 'null'] },
        destination: { bsonType: 'string', description: 'Destination is required' },
        purpose: { bsonType: 'string', description: 'Purpose is required' },
        departureDate: { bsonType: 'date', description: 'Departure date is required' },
        returnDate: { bsonType: ['date', 'null'] },
        expectedDeparture: { bsonType: ['date', 'null'] },
        actualDeparture: { bsonType: ['date', 'null'] },
        expectedReturn: { bsonType: ['date', 'null'] },
        actualReturn: { bsonType: ['date', 'null'] },
        passengers: { bsonType: 'array' },
        startingMileage: { bsonType: ['int', 'null'] },
        endingMileage: { bsonType: ['int', 'null'] },
        distanceCovered: { bsonType: ['int', 'null'] },
        status: { enum: ['pending', 'requested', 'supervisor_approved', 'fleet_approved', 'vehicle_assigned', 'in_progress', 'completed', 'rejected', 'approved', 'in-progress'], description: 'Must be a valid status' },
        history: { bsonType: 'array' },
        createdAt: { bsonType: 'date' },
        updatedAt: { bsonType: 'date' },
      },
    },
  },
  indexes: [
    { key: { tripId: 1 }, options: { unique: true } },
    { key: { vehicleId: 1 } },
    { key: { userId: 1 } },
    { key: { driverId: 1 } },
    { key: { requestingOfficerId: 1 } },
    { key: { status: 1 } },
    { key: { departureDate: 1 } },
  ],
};
