export default {
  collection: 'vehicles',
  validator: {
    $jsonSchema: {
      bsonType: 'object',
      required: ['name', 'plateNumber'],
      properties: {
        name: { bsonType: 'string', description: 'Name is required' },
        plateNumber: { bsonType: 'string', description: 'Plate number is required' },
        employeeNo: { bsonType: ['string', 'null'] },
        category: { bsonType: 'string' },
        capacity: { bsonType: 'int' },
        description: { bsonType: 'string' },
        status: { bsonType: 'string' },
        mileage: { bsonType: 'int' },
        make: { bsonType: ['string', 'null'] },
        model: { bsonType: ['string', 'null'] },
        year: { bsonType: ['int', 'null'] },
        fuelType: { bsonType: ['string', 'null'] },
        insuranceExpiry: { bsonType: ['date', 'null'] },
        inspectionExpiry: { bsonType: ['date', 'null'] },
        serviceSchedule: { bsonType: ['date', 'null'] },
        currentMileage: { bsonType: ['int', 'null'] },
        assignedDriverId: { bsonType: ['string', 'null'] },
        assignedParkingLotId: { bsonType: ['string', 'null'] },
        assignedStationId: { bsonType: ['string', 'null'] },
        qrCode: { bsonType: ['string', 'null'] },
        qrGeneratedYear: { bsonType: ['int', 'null'] },
        qrStatus: { bsonType: 'string' },
        deactivatedAt: { bsonType: ['date', 'null'] },
        createdAt: { bsonType: 'date' },
        updatedAt: { bsonType: 'date' },
      },
    },
  },
  indexes: [
    { key: { plateNumber: 1 }, options: { unique: true } },
    { key: { status: 1 } },
    { key: { category: 1 } },
    { key: { assignedStationId: 1 } },
    { key: { insuranceExpiry: 1 }, options: { sparse: true } },
    { key: { inspectionExpiry: 1 }, options: { sparse: true } },
    { key: { qrStatus: 1 } },
  ],
};
